package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * CentroCosto generated by hbm2java
 */
@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(schema = "public", name = "centro_costo")
public class CentroCosto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "cco_id", unique = true, nullable = false)
	private int ccoId;
	
	@Column(name = "cco_code", nullable = false)
	private String ccoCode;
	
	@Column(name = "cco_nombre", nullable = false)
	private String ccoNombre;
	
	@Column(name = "cco_descripcion")
	private String ccoDescripcion;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "centroCosto")
	private Set<Proyecto> proyectos = new HashSet<>(0);
}
