package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(schema = "public", name = "cliente")
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "cli_id", unique = true, nullable = false)
	private int cliId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", nullable = false)
	private Pais pais;

	@Column(name = "cli_nombre")
	private String cliNombre;

	@Column(name = "cli_razon_social")
	private String cliRazonSocial;

	@Column(name = "cli_rut")
	private String cliRut;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	private Set<Proyecto> proyectos = new HashSet<>(0);

}
