package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Comuna generated by hbm2java
 */
@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(schema = "public", name = "comuna")
public class Comuna implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "com_id", unique = true, nullable = false)
	private int comId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_region", nullable = false)
	private Region region;

	@Column(name = "com_descripcion", nullable = false, length = 100)
	private String comDescripcion;

}
