package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Estructura generated by hbm2java
 */
@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(schema = "public", name = "estructura")
public class Estructura implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "est_id", unique = true, nullable = false)
	private int estId;

	@Column(name = "est_nombre", nullable = false)
	private String estNombre;

	@Column(name = "est_tasa_costo", precision = 10)
	private BigDecimal estTasaCosto;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estructura")
	private Set<PersonaEstructura> personaEstructuras = new HashSet<>(0);

}
