package org.ms.timepro.manager.entity;
// Generated 14-09-2024 21:12:12 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Pais generated by hbm2java
 */
@Entity
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Table(schema = "public", name = "pais")
public class Pais implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "pai_id", unique = true, nullable = false)
	private int paiId;

	@Column(name = "pai_descripcion", nullable = false, length = 100)
	private String paiDescripcion;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	private Set<Cliente> clientes = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisByIdPaisNacionalidad")
	private Set<Persona> personasForIdPaisNacionalidad = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	private Set<Compania> companias = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	private Set<Region> regions = new HashSet<>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paisByIdPaisResidencia")
	private Set<Persona> personasForIdPaisResidencia = new HashSet<>(0);
}
