package org.ms.timepro.manager.entity;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "persona")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Persona implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "per_id", unique = true, nullable = false)
    private int perId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pais_nacionalidad")
    private Pais paisByIdPaisNacionalidad;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pais_residencia")
    private Pais paisByIdPaisResidencia;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_supervisor")
    private Persona persona;

    @Column(name = "per_nombre", nullable = false)
    private String perNombre;

    @Column(name = "per_ape_paterno")
    private String perApePaterno;

    @Column(name = "per_ape_materno")
    private String perApeMaterno;

    @Column(name = "per_rut_dni")
    private String perRutDni;

    @Column(name = "per_email_personal")
    private String perEmailPersonal;

    @Column(name = "per_email_corporativo")
    private String perEmailCorporativo;

    @Column(name = "per_oficina_origen")
    private String perOficinaOrigen;

    @Column(name = "per_nacionalidad")
    private String perNacionalidad;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    private Set<MetodoPago> metodoPagos = new HashSet<MetodoPago>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    private Set<PersonaEstructura> personaEstructuras = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    private Set<Asignacion> asignacions = new HashSet<>(0);

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
    private Set<Persona> personas = new HashSet<>(0);
}