package org.ms.timepro.manager.entity;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Pricing generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "pricing")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Pricing implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "pri_id", unique = true, nullable = false)
    private int priId;

    @Column(name = "pri_target_marging", precision = 10)
    private BigDecimal priTargetMarging;

    @Column(name = "pri_revenue", precision = 10)
    private BigDecimal priRevenue;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "pricing")
    private Set<Proyecto> proyectos = new HashSet<>(0);
}
