package org.ms.timepro.manager.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "proyecto")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Proyecto implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "pry_id", unique = true, nullable = false)
    private int pryId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_centro_costo", nullable = false)
    private CentroCosto centroCosto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_cliente", nullable = false)
    private Cliente cliente;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_compania", nullable = false)
    private Compania compania;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pricing", nullable = false)
    private Pricing pricing;

    @Column(name = "pry_nombre", nullable = false)
    private String pryNombre;

    @Temporal(TemporalType.DATE)
    @Column(name = "pry_fecha_inicio", length = 13)
    private Date pryFechaInicio;

    @Temporal(TemporalType.DATE)
    @Column(name = "pry_fecha_fin", length = 13)
    private Date pryFechaFin;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "proyecto")
    private Set<Asignacion> asignaciones = new HashSet<>(0);
}
