package org.ms.timepro.manager.entity;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "region")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Region implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "reg_id", unique = true, nullable = false)
    private int regId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_pais", nullable = false)
    private Pais pais;

    @Column(name = "reg_descripcion", nullable = false, length = 100)
    private String regDescripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
    private Set<Comuna> comunas = new HashSet<>(0);
}
