package org.ms.timepro.manager.entity;

import java.math.BigDecimal;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TimeReport generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "time_report")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TimeReport implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "trp_id", unique = true, nullable = false)
    private int trpId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_asignacion", nullable = false)
    private Asignacion asignacion;

    @Column(name = "trp_horas", precision = 10)
    private BigDecimal trpHoras;

    @Column(name = "trp_tarifa", precision = 10)
    private BigDecimal trpTarifa;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "trp_fecha_inicio", nullable = false, length = 29)
    private Date trpFechaInicio;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "trp_fecha_fin", nullable = false, length = 29)
    private Date trpFechaFin;

    @Column(name = "trp_horas_totales")
    private Long trpHorasTotales;
}
