package org.ms.timepro.manager.entity;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * TipoPago generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "tipo_pago")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TipoPago implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
    @Column(name = "tpg_id", unique = true, nullable = false)
    private int tpgId;

    @Column(name = "tpg_nombre")
    private String tpgNombre;

    @Column(name = "tpg_descripcion")
    private String tpgDescripcion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPago")
    private Set<MetodoPago> metodoPago = new HashSet<>();
}
